### ISSUE TITLE
resolveSassPath ignores explicit file names.

### ISSUE THREAD

**Issue by jsg2021** [xzyfer/sass-graph#14]
I just updated [sass-loader](jtangelder/sass-loader#497a6f6b32b4cf1ae0b512539589b2789b5ee624) in my project and can't get my project built.  I've narrowed it down to this...

This is where the problem is:

```
var sassPathName = sassPath.replace(/\.\w+$/, '');
  ...
var scssPath = path.normalize(loadPaths[i] + "/" + sassPathName + ".scss");
```

Can we make it take the `sassPath` directly when normalizing? then when not found attempt to add known extensions?

In the project referenced above I have several font imports that are just simple css files:
```
@import "../fonts/fontname/index.css"
```

**Comment by xzyfer** [comment]
Sorry I haven't been receiving GH emails.

I don't believe I'm fully understanding the problem. Could you please show a specific use-case you're experiencing.

**Comment by jsg2021** [comment]
I have a few font packages where there is an index.css file that has all the font definitions.  Instead of renaming the css file to scss I left them as css so it could be shared.  When `sass-graph` was introduced to `sass-loader` my builds started failing.  I'm currently working around the issue by placing a dummy .scss file of the same name as the .css file to make sass-graph happy.

**Comment by xzyfer** [comment]
If I'm understanding correctly sounds like https://github.com/xzyfer/sass-graph/pull/20 may had fixed this issue. Can you confirm?

**Comment by jsg2021** [comment]
That PR changes the game.  If you omit imports from the graph, your graph will not be complete.  If the graph is used by something to track all imports, sass-graph no longer meets their needs.  

For my needs its probably sufficient.  My .css files do not change ever, so sass-loader's report of files to watch to WebPack won't include those css files... the libsass does the actual work, so we're essentially just talking about dev meta data.

**Comment by xzyfer** [comment]
There's a couple separate issues here. The intention of the project is to generate a graph of depencies as seen by the Ruby Sass interpreter/watcher. 

So this behaviour is intentional since Ruby Sass ignores @imported .css AFAIK (please correct me if I'm wrong).

The PR mentioned previously addresses a similar issue where in if a file doesn't exist on disk we're throwing, which doesn't for gem'd imports like compass.

**Comment by jsg2021** [comment]
makes sense :) Then I'll count this as fixed when that is released.
