### ISSUE TITLE
Sass-graph fails on compass imports

### ISSUE THREAD

**Issue by kevin-smets** [xzyfer/sass-graph#16]
```
@import "compass";
@import "compass/reset";
```

Defining this in your scss will cause sass-graph to fail silently. Each and every compass import starts with compass, so maybe these could be whitelisted?

**Comment by xzyfer** [comment]
Sorry I haven't been receiving GH emails.

Since Libsass now supports custom importers I suspect the correct way to deal with this is to simply ignore paths that don't resolve.

**Comment by kevin-smets** [comment]
I added support for custom imports in #20

**Comment by scottkellum** [comment]
> Each and every compass import starts with compass, so maybe these could be whitelisted

If someone installs a plugin through Compass it may be different. Maybe `@import 'modular-scale';` or `@import 'susy';`

**Comment by kevin-smets** [comment]
The way I built it now in #20 , this will cover these use cases as well :). Still a good point thought, thanks.

**Comment by xzyfer** [comment]
Fixed in https://github.com/xzyfer/sass-graph/pull/20 - thanks @kevin-smets !
