### ISSUE TITLE
resolveSassPath misses nested dependencies with the same name

### ISSUE THREAD

**Issue by averyvery** [xzyfer/sass-graph#21]
Having an unusual issue with sass-graph:

* I have a `components/_index.scss` that imports `nav/index` and `overlay/index`
* Both `overlay/_index.scss` and `nav/_index.scss` import files (in their respective directories) named `_wrapper.scss`
* Both index files are included in the graph, but only ONE `_wrapper.scss` is included in the graph. The `resolveSassPath` method seems to count `nav/_wrapper.scss` twice instead of counting `overlay/_wrapper.scss`
* This seems to be happening because `resolveSassPath` returns the first match for a filename + loadPath that it finds.

I've recreated this as a test case in a branch here, and proposed a fix: 

* https://github.com/averyvery/sass-graph/tree/same-name-dependency-test/test - tests has dependencies with the same name
* https://github.com/averyvery/sass-graph/blob/same-name-dependency-test/sass-graph.js#L11 - `resolveSassPath` now returns an array of matches, instead of the first match it encounters

**Comment by xzyfer** [comment]
Thank you. This has been fixed in sass-graph@2.0.0.
