### ISSUE TITLE
sass-graph doesn't parse .sass files

### ISSUE THREAD

**Issue by averyvery** [xzyfer/sass-graph#22]
Most sass parsers parse .sass file ("indented syntax") as well as .scss syntax. I create a branch — https://github.com/averyvery/sass-graph/blob/parse-sass-filetypes/ — that modifies sass-graph to allow for this.

* https://github.com/averyvery/sass-graph/blob/parse-sass-filetypes/sass-graph.js — (logic is repetitive; could be reorganized to prevent duplication)
* https://github.com/averyvery/sass-graph/blob/parse-sass-filetypes/parse-imports.js — alt. regex for parsing .sass imports
* https://github.com/averyvery/sass-graph/tree/parse-sass-filetypes/test — updating test suite to include some .sass files

**Comment by kevin-smets** [comment]
Oooh, that's nice :). Even though I started converting most of my stuff from sass to scss this would be a great feature (since sass will never drop the old syntax). Sadly, other 3rd party tools are dropping support for the old syntax, such as scss-lint which dropped it after 0.27.0...

**Comment by xzyfer** [comment]
I think this should mostly work now.

Sass graph only really needs to know who to parse import statement which
are mostly the same across the two syntaxes.

**Comment by averyvery** [comment]
I still see direct references to `.scss` in https://github.com/xzyfer/sass-graph/blob/master/sass-graph.js — these won't work with .sass files.

**Comment by vegetableman** [comment]
Facing this same issue. I reported it to the wrong repo. Check out:- https://github.com/sass/node-sass/issues/851#issuecomment-91892598.

**Comment by xzyfer** [comment]
Fixed by #27 - thanks @vegetableman
