### ISSUE TITLE
Take over the npm package

### ISSUE THREAD

**Issue by maxmx** [xzyfer/sass-graph#25]
Could you take over the gulp-sass-graph package?

Thanks

https://docs.npmjs.com/misc/disputes

**Comment by xzyfer** [comment]
Thanks for the link @maxmx. I know the original author, I'll ask him. Shouldn't be a problem.

**Comment by glen-84** [comment]
@xzyfer Did you ask?

**Comment by xzyfer** [comment]
@glen-84 I'd honestly forgotten. I had npm access. I'll try to get github access today.

**Comment by xzyfer** [comment]
I now own gulp-sass-graph. PRs welcome.
