### ISSUE TITLE
Gulp plugin

### ISSUE THREAD

**Issue by berstend** [xzyfer/sass-graph#26]
I couldn't find any gulp packages wrapping sass-graph so I quickly created one:
https://github.com/berstend/gulp-sass-inheritance

Feel free to link it in your README.

**Comment by xzyfer** [comment]
Hi @berstend,

[gulp-sass-graph](https://github.com/lox/gulp-sass-graph) was created by the original author of this project. It's out of date, but authoring a PR there is probably the better way to go about doing this.

**Comment by berstend** [comment]
I saw the outdated plugin you've mentioned but needed something working on NPM quickly.

Will issue a PR to gulp-sass-graph when I find the time. :-)

Thanks!

**Comment by glen-84** [comment]
This plug-in doesn't appear to be maintained. Still using `sass-graph@^1.2.0` and no recent PR activity. :disappointed:

**Comment by xzyfer** [comment]
Feel free to maintain your own. I have no interest in doing so.
