### ISSUE TITLE
Feature: Importers and functions

### ISSUE THREAD

**Issue by npbenjohnson** [xzyfer/sass-graph#44]
node-sass uses sass-graph to watch it's dependency tree. Because sass-graph doesn't know how to handle [importers](https://github.com/sass/node-sass#importer--v200---experimental) and [functions](https://github.com/sass/node-sass#functions--v300---experimental), mapped imports aren't watched.

**Comment by xzyfer** [comment]
I'm fairly certain it's not possible to graph importers. Even so it's out
of the scope of this project. Sass graph isn't about Node Sass it's about
Sass in general.
