### ISSUE TITLE
sass-graph 2.2.0 and issue with node-sass: Unexpected token import

### ISSUE THREAD

**Issue by floviolleau** [xzyfer/sass-graph#76]
Hello,

I use node-sass which is a dependency of my project and node-sass use sass-graph with the resolving number: "sass-graph": "^2.1.1".

Since you published a new version 2.2.0, node-sass  use now the 2.2.0 version and when I run:
```
node-sass --include-path demo/digital-style/sass demo/digital-style/sass/style-ss.scss -o demo/app/css/
```

I have this error:
```
C:\myRepo\node_modules\scss-tokenizer\lib\entry.js:1
(function (exports, require, module, __filename, __dirname) { import Input from './input';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\myRepo\node_modules\scss-tokenizer\node_modules\babel-core\lib\api\register\node.js:214:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

I don't know if it's the good place to report.
Can you help me?

Kind regards.

**Comment by floviolleau** [comment]
Maybe linked to https://github.com/sass/node-sass/issues/1957

**Comment by xzyfer** [comment]
Thanks for the report. I've unpublished 2.2.0 until I have time to look into it.

**Comment by WaldoJeffers** [comment]
@xzyfer Thanks for your quick answer. It seems like `scss-tokenizer` is not a CommonJs module, meaning it's not node-compatible. Strangely, the [index file](https://github.com/sasstools/scss-tokenizer/blob/master/index.js) is a CommonJs module, but the [rest of the code](https://github.com/sasstools/scss-tokenizer/blob/master/lib/entry.js) is using ES6 module imports. Is this intended ?

**Comment by xzyfer** [comment]
`scss-tokenizer` is an active work in progress. I must have published the source files and not the transpiled output.

**Comment by jharris4** [comment]
Ahh, I had just submitted a PR (https://github.com/sasstools/scss-tokenizer/pull/9). `scs-tokenizer` was still using babel 5.x which may have been part of the problem...
