### ISSUE TITLE
yarn still picking up unpublished 2.2.0 version

### ISSUE THREAD

**Issue by jharris4** [xzyfer/sass-graph#78]
I realize version 2.2.0 was unpublished, but `yarn` still insists on installing it for some reason.

I've filed an issue against yarn for this (https://github.com/yarnpkg/yarn/issues/3274), but in the meantime, I was hoping that you might consider releasing a new version of 'sass-graph' on npm to get people like me out of this mess...

Thanks

**Comment by xzyfer** [comment]
Published 2.2.2 with a fixed scss-tokenizer
