### ISSUE TITLE
includePaths to resolve import path

### ISSUE THREAD

**Issue by davidcazalis** [xzyfer/sass-graph#87]
Hi there. I don't know if it's an issue, but it could be nice to have an [includePaths](https://github.com/sass/node-sass#includepaths) option, like node-sass.

In my case, I have to import sass files from some modules, in my `node_modules` folder, but sass-graph seems to not detect them at all.

In this exemple, I have :

```scss
@import "lib/foo";
@import "foo-module/foo"; // In ./node_modules/foo-module/foo.scss
```

But sass-graph only detect the file in `lib/foo`. Not the file in `node_modules/foo-module`, which isn't a surprise, because it have no way to detect that `foo-module/foo.scss` is in my `node_modules` folder.

Could we have an elegant solution for this case, or I am it doing wrong ?

Awesome project btw, save me hours of headache.

**Comment by xzyfer** [comment]
This module is used by node-sass' watcher. We have an equivalent to includePaths called [loadpaths](https://github.com/xzyfer/sass-graph#loadpaths).
