### ISSUE TITLE
Imports aren't properly resolved

### ISSUE THREAD

**Issue by Hoffs** [xzyfer/sass-graph#90]
Not sure if it's intended but if I specify `loadsPaths: ['./src', './node_modules']` and parse directory `src`  I dont get any imports/importedBy paths. If I specify paths as `['./']` it resolves them fine. 
My folder structure would be:
```
node_modules/.....
src/.....
```
so in reality I include both paths that are included by './' either way, but the result is different.

**Comment by Hoffs** [comment]
Well so I did some digging and I see whats happening. Its probably how its supposed to be, but basically if you have `@import 'src/a.scss'` and load path `'./src'` in the end it will be looking at `./src/src/a.scss` because of:
```javascript
scssPath = path.normalize(loadPaths[i] + '/' + sassPathName + '.' + extensions[j]);
```
so it seems it wants root path based on your imports. This could be changed to check for files and load paths that share same folder (like `./src` matches import `src/a.scss`) but that might have side effects.

**Comment by xzyfer** [comment]
You're correcy about the behvaiour. This emulates the import algorithm in
Sass, which what this library is all about.
