### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by char0n** [xzyfer/sass-graph#93]
Hello, is it possible to incorporate the LICENSE file inside the repo and npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the repo nor npm package the code is proprietary and the world cannot use it. 

Thank you

**Comment by char0n** [comment]
Thank you! The PR has been merged. Is there a plan for a patch release here ?

**Comment by char0n** [comment]
Is there some development here ? Would it be possible to release 3.0.1 with the license ? We are currently blocked on using node-sass because of this small inconvenience.

**Comment by xzyfer** [comment]
Published 3.0.1

**Comment by char0n** [comment]
Thank you very much.
