### ISSUE TITLE
Lodash vulnerability

### ISSUE THREAD

**Issue by patricksmms** [xzyfer/sass-graph#95]
There's [a security vulnerability](https://david-dm.org/xzyfer/sass-graph) in the version of loadash used here.

Using the latest seems to solve the issue.

Could someone bump the version and publish it to npm, please?

Much appreciated :pray:

**Comment by xzyfer** [comment]
PRs are welcome :)

**Comment by patricksmms** [comment]
@xzyfer can you please publish to npm?

**Comment by xzyfer** [comment]
Published 3.0.2
